PUT http://localhost:3000/api/entries/62142f1b6185452833a68b81
Content-Type: application/json

{
    "author": "updated",
    "name": "updated",
    "year": 9999,
    "type": "updated2",
    "cover": ""
}